// <auto-generated />
namespace Marjani.Peyment.Bitcoin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201601162103306_updateOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
