// <auto-generated />
namespace Marjani.Peyment.Bitcoin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class secret : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secret));
        
        string IMigrationMetadata.Id
        {
            get { return "201601152217598_secret"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
